# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c4326e878c5ae9cf78363d89b2e76a728bf3f0dfe14d98457e31edddc5d815f0ea9010c02d1103020ef7a448709b452725cb20e295151dbfafa4dd0c7eac35b

test:
  secret_key_base: bf75b3efeb06878f8e4f6ba97f7abdf299a332b088bf0900092bb92aa1d12aae40e7c1469d41193f666403679242a04a6ad5ab349e1c8910c6dbc973a5e6ac42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
